"""Verified official career sources for the China job-search catalog."""

from __future__ import annotations

from typing import Any, Dict, Tuple


OFFICIAL_CAREER_SOURCES_CN: Tuple[Dict[str, Any], ...] = (
    {
        "source_id": "src_cn_tencent",
        "company_name": "腾讯",
        "official_domain": "hr.tencent.com",
        "source_url": "https://hr.tencent.com/zh-cn/",
        "delegated_domains": ["careers.tencent.com", "zhaopin.tencent.com"],
        "source_type": "company_careers",
        "industry": "互联网与科技",
        "recruitment_channels": ["campus", "experienced", "internship"],
        "support_level": "manual_import",
        "verified_at": "2026-08-10",
        "refresh_policy": "disabled",
        "automation_allowed": False,
        "policy_url": "https://careers.tencent.com/m/zh-cn/termsservice.html",
    },
    {
        "source_id": "src_cn_huawei",
        "company_name": "华为",
        "official_domain": "career.huawei.com",
        "source_url": "https://career.huawei.com/cn/social-recruitment",
        "source_type": "company_careers",
        "industry": "通信与硬件",
        "recruitment_channels": ["campus", "experienced", "internship"],
        "support_level": "manual_import",
        "verified_at": "2026-08-10",
        "refresh_policy": "disabled",
        "automation_allowed": False,
    },
    {
        "source_id": "src_cn_bytedance",
        "company_name": "字节跳动",
        "official_domain": "jobs.bytedance.com",
        "source_url": "https://jobs.bytedance.com/",
        "source_type": "company_careers",
        "industry": "互联网与科技",
        "recruitment_channels": ["campus", "experienced", "internship"],
        "support_level": "manual_import",
        "verified_at": "2026-08-10",
        "refresh_policy": "disabled",
        "automation_allowed": False,
    },
    {
        "source_id": "src_cn_meituan",
        "company_name": "美团",
        "official_domain": "zhaopin.meituan.com",
        "source_url": "https://zhaopin.meituan.com/web/social",
        "source_type": "company_careers",
        "industry": "互联网与科技",
        "recruitment_channels": ["campus", "experienced", "internship"],
        "support_level": "manual_import",
        "verified_at": "2026-08-10",
        "refresh_policy": "disabled",
        "automation_allowed": False,
    },
    {
        "source_id": "src_cn_baidu",
        "company_name": "百度",
        "official_domain": "talent.baidu.com",
        "source_url": "https://talent.baidu.com/jobs/social",
        "job_source_url": "https://talent.baidu.com/jobs/list?projectType=1",
        "source_type": "company_careers",
        "industry": "互联网与科技",
        "recruitment_channels": ["campus", "experienced", "internship"],
        "support_level": "structured_import",
        "verified_at": "2026-08-10",
        "refresh_policy": "disabled",
        "automation_allowed": False,
    },
    {
        "source_id": "src_cn_alibaba",
        "company_name": "阿里巴巴",
        "official_domain": "campus-talent.alibaba.com",
        "source_url": "https://campus-talent.alibaba.com/campus/gov",
        "source_type": "company_careers",
        "industry": "互联网与科技",
        "recruitment_channels": ["campus", "internship"],
        "support_level": "manual_import",
        "verified_at": "2026-08-10",
        "refresh_policy": "disabled",
        "automation_allowed": False,
    },
    {
        "source_id": "src_cn_xiaomi",
        "company_name": "小米",
        "official_domain": "hr.xiaomi.com",
        "source_url": "https://hr.xiaomi.com/",
        "source_type": "company_careers",
        "industry": "消费电子与科技",
        "recruitment_channels": ["campus", "experienced", "internship"],
        "support_level": "manual_import",
        "verified_at": "2026-08-10",
        "refresh_policy": "disabled",
        "automation_allowed": False,
    },
    {
        "source_id": "src_cn_oppo",
        "company_name": "OPPO",
        "official_domain": "careers.oppo.com",
        "source_url": "https://careers.oppo.com/",
        "source_type": "company_careers",
        "industry": "消费电子与科技",
        "recruitment_channels": ["campus", "experienced", "internship"],
        "support_level": "manual_import",
        "verified_at": "2026-08-10",
        "refresh_policy": "disabled",
        "automation_allowed": False,
    },
    {
        "source_id": "src_cn_vivo",
        "company_name": "vivo",
        "official_domain": "hr.vivo.com",
        "source_url": "https://hr.vivo.com/index.html",
        "source_type": "company_careers",
        "industry": "消费电子与科技",
        "recruitment_channels": ["campus", "experienced", "internship"],
        "support_level": "manual_import",
        "verified_at": "2026-08-10",
        "refresh_policy": "disabled",
        "automation_allowed": False,
    },
    {
        "source_id": "src_cn_lenovo",
        "company_name": "联想",
        "official_domain": "jobs.lenovo.com",
        "source_url": "https://jobs.lenovo.com/",
        "source_type": "company_careers",
        "industry": "消费电子与科技",
        "recruitment_channels": ["experienced"],
        "support_level": "manual_import",
        "verified_at": "2026-08-10",
        "refresh_policy": "disabled",
        "automation_allowed": False,
    },
    {
        "source_id": "src_cn_zte",
        "company_name": "中兴通讯",
        "official_domain": "job.zte.com.cn",
        "source_url": "https://job.zte.com.cn/cn/",
        "source_type": "company_careers",
        "industry": "通信与硬件",
        "recruitment_channels": ["campus", "experienced", "internship"],
        "support_level": "manual_import",
        "verified_at": "2026-08-10",
        "refresh_policy": "disabled",
        "automation_allowed": False,
    },
    {
        "source_id": "src_cn_dji",
        "company_name": "大疆",
        "official_domain": "we.dji.com",
        "source_url": "https://we.dji.com/zh-CN/campus/position",
        "source_type": "company_careers",
        "industry": "智能硬件与制造",
        "recruitment_channels": ["campus", "experienced", "internship"],
        "support_level": "manual_import",
        "verified_at": "2026-08-10",
        "refresh_policy": "disabled",
        "automation_allowed": False,
    },
    {
        "source_id": "src_cn_byd",
        "company_name": "比亚迪",
        "official_domain": "job.byd.com",
        "source_url": "https://job.byd.com/portal/pc/",
        "source_type": "company_careers",
        "industry": "汽车与新能源",
        "recruitment_channels": ["campus", "experienced", "internship"],
        "support_level": "manual_import",
        "verified_at": "2026-08-10",
        "refresh_policy": "disabled",
        "automation_allowed": False,
    },
    {
        "source_id": "src_cn_icbc",
        "company_name": "中国工商银行",
        "official_domain": "job.icbc.com.cn",
        "source_url": "https://job.icbc.com.cn/pc/index.html",
        "source_type": "company_careers",
        "industry": "金融",
        "recruitment_channels": ["campus", "experienced", "internship"],
        "support_level": "manual_import",
        "verified_at": "2026-08-10",
        "refresh_policy": "disabled",
        "automation_allowed": False,
    },
    {
        "source_id": "src_cn_cmb",
        "company_name": "招商银行",
        "official_domain": "career.cmbchina.com",
        "source_url": "https://career.cmbchina.com/campus/home",
        "source_type": "company_careers",
        "industry": "金融",
        "recruitment_channels": ["campus", "experienced", "internship"],
        "support_level": "manual_import",
        "verified_at": "2026-08-10",
        "refresh_policy": "disabled",
        "automation_allowed": False,
    },
    {
        "source_id": "src_cn_microsoft",
        "company_name": "Microsoft",
        "official_domain": "careers.microsoft.com",
        "source_url": "https://careers.microsoft.com/v2/global/en/locations/gcr.html",
        "job_source_url": "https://careers.microsoft.com/v2/global/en/locations/gcr.html",
        "delegated_domains": ["apply.careers.microsoft.com"],
        "source_type": "company_careers",
        "industry": "软件与云服务",
        "recruitment_channels": ["campus", "experienced", "internship"],
        "support_level": "structured_import",
        "verified_at": "2026-08-12",
        "refresh_policy": "disabled",
        "automation_allowed": False,
    },
    {
        "source_id": "src_cn_sap",
        "company_name": "SAP",
        "official_domain": "jobs.sap.com",
        "source_url": "https://jobs.sap.com/go/SAP-Jobs-in-China/881201/",
        "job_source_url": "https://jobs.sap.com/go/SAP-Jobs-in-China/881201/",
        "source_type": "company_careers",
        "industry": "企业软件",
        "recruitment_channels": ["campus", "experienced", "internship"],
        "support_level": "structured_import",
        "verified_at": "2026-08-12",
        "refresh_policy": "disabled",
        "automation_allowed": False,
    },
    {
        "source_id": "src_cn_siemens",
        "company_name": "Siemens",
        "official_domain": "jobs.siemens.com.cn",
        "source_url": "https://jobs.siemens.com.cn/",
        "source_type": "company_careers",
        "industry": "工业与智能制造",
        "recruitment_channels": ["campus", "experienced", "internship"],
        "support_level": "manual_import",
        "verified_at": "2026-08-12",
        "refresh_policy": "disabled",
        "automation_allowed": False,
    },
    {
        "source_id": "src_cn_pg",
        "company_name": "P&G",
        "official_domain": "careers.pg.com.cn",
        "source_url": "https://careers.pg.com.cn/cn/en",
        "delegated_domains": ["www.pgcareers.com"],
        "source_type": "company_careers",
        "industry": "消费品",
        "recruitment_channels": ["campus", "experienced", "internship"],
        "support_level": "manual_import",
        "verified_at": "2026-08-12",
        "refresh_policy": "disabled",
        "automation_allowed": False,
    },
    {
        "source_id": "src_cn_unilever",
        "company_name": "Unilever",
        "official_domain": "careers.unilever.com",
        "source_url": "https://careers.unilever.com/en/china",
        "source_type": "company_careers",
        "industry": "消费品",
        "recruitment_channels": ["campus", "experienced", "internship"],
        "support_level": "manual_import",
        "verified_at": "2026-08-12",
        "refresh_policy": "disabled",
        "automation_allowed": False,
    },
    {
        "source_id": "src_cn_deloitte",
        "company_name": "Deloitte",
        "official_domain": "www.deloitte.com",
        "source_url": "https://www.deloitte.com/cn/en/cn-careers.html",
        "delegated_domains": ["ehjobs.deloitte.com.cn"],
        "source_type": "company_careers",
        "industry": "专业服务",
        "recruitment_channels": ["campus", "experienced", "internship"],
        "support_level": "manual_import",
        "verified_at": "2026-08-12",
        "refresh_policy": "disabled",
        "automation_allowed": False,
    },
    {
        "source_id": "src_cn_ey",
        "company_name": "EY",
        "official_domain": "www.ey.com",
        "source_url": "https://www.ey.com/en_cn/careers",
        "delegated_domains": [
            "app.mokahr.com",
            "careers.ey.com.cn",
            "ey.hotjob.cn",
            "hkcareers.ey.com.cn",
        ],
        "source_type": "company_careers",
        "industry": "专业服务",
        "recruitment_channels": ["campus", "experienced", "internship"],
        "support_level": "manual_import",
        "verified_at": "2026-08-12",
        "refresh_policy": "disabled",
        "automation_allowed": False,
    },
    {
        "source_id": "src_cn_hsbc",
        "company_name": "HSBC",
        "official_domain": "www.about.hsbc.com.cn",
        "source_url": "https://www.about.hsbc.com.cn/careers",
        "delegated_domains": [
            "apply.careers.hsbc.com",
            "portal.careers.hsbc.com",
        ],
        "source_type": "company_careers",
        "industry": "金融",
        "recruitment_channels": ["campus", "experienced", "internship"],
        "support_level": "manual_import",
        "verified_at": "2026-08-12",
        "refresh_policy": "disabled",
        "automation_allowed": False,
    },
)
